[default]

NET = "NET1"

TRAIN_BATCH_SIZE = 10
VALID_BATCH_SIZE = 10
NUM_EPOCHS = 100

OPTIMIZER = "ADAM"
LR_DECAY_RATE = 0.5
PATIENCE = 8
EARLY_STOP = 16

VALIDATION_INTERVAL = 1

KFOLD_N = 5
KFOLD_I = 0

DEBUG = false
