[net]
name = "net1"

[dataset]
name = "dataset1"
kfold_N = 5
kfold_I = 0

[agent]
name = "agent1"
num_epochs = 10

train_batch_size = 64
valid_batch_size = 64

train_workers = 8
valid_workers = 8

validation_interval = 1

[optim]
name = "ADAM"

lr = 0.001
lr_decay_rate = 0.5
lr_decay_patience = 8
early_stop = 16

[loss]
something = 0
