[default]

NET = "NET1"

DATASET = "DATASET1"
KFOLD_N = 5
KFOLD_I = 0

NUM_EPOCHS = 100
TRAIN_BATCH_SIZE = 64
VALID_BATCH_SIZE = 64
VALIDATION_INTERVAL = 1
FULL_VALIDATION_POINT = 95

OPTIMIZER = "ADAM"
LR_DECAY_RATE = 0.5
PATIENCE = 8
EARLY_STOP = 16

DEBUG = false
