[default]

NET = "NETWORK_NAME"

TRAIN_BATCH_SIZE = 10
VALIDATION_BATCH_SIZE = 10
NUM_EPOCHS = 100

OPTIMIZER = "ADAM"
LR_DECAY_RATE = 0.5
PATIENCE = 8
EARLY_STOP = 16

VALIDATION_INTERVAL = 10

KFOLD_I = 0
KFOLD_N = 5

DEBUG = false
